#!/usr/bin/python3

WHITE_COLOR = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)
YELLOW_COLOR = (255, 255, 0)

START_GAME_LABEL = "Start Game"
GAME_SETTINGS_LABEL = "Game Settings"
QUIT_GAME_LABEL = "Quit Game"

MENU_CAPTION = "Menu"
GAME_CAPTION = "Game"
